version: "3.8"
services:
  db:
    image: postgres:16
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=cu
      - POSTGRES_USER=cu
      - POSTGRES_PASSWORD=cu
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql+psycopg://cu:cu@db:5432/cu
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/data
    depends_on:
      - db
    # In a full deployment, compose can also include xvfb/noVNC as separate services

volumes:
  backend_data: {}
  pg_data: {}


